[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chaitanya-3012", email = "chaitanyanevse3012@email.com" }
]
requires-python = ">=3.13"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy[asyncio]",
  "asyncpg",
  "pydantic",
  "pydantic-settings",
  "scikit-learn",
  "apscheduler",
  "httpx",
  "python-multipart",
]

[project.scripts]
backend = "backend.main:app"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
